const mapLanguageId = (platform: string, id: number) => {
  const languages: any = {
    Macintosh: {
      '0': { lang: 'English' },
      '1': { lang: 'French' },
      '2': { lang: 'German' },
      '3': { lang: 'Italian' },
      '4': { lang: 'Dutch' },
      '5': { lang: 'Swedish' },
      '6': { lang: 'Spanish' },
      '7': { lang: 'Danish' },
      '8': { lang: 'Portuguese' },
      '9': { lang: 'Norwegian' },
      '10': { lang: 'Hebrew' },
      '11': { lang: 'Japanese' },
      '12': { lang: 'Arabic' },
      '13': { lang: 'Finnish' },
      '14': { lang: 'Greek' },
      '15': { lang: 'Icelandic' },
      '16': { lang: 'Maltese' },
      '17': { lang: 'Turkish' },
      '18': { lang: 'Croatian' },
      '19': { lang: 'Chinese (traditional)' },
      '20': { lang: 'Urdu' },
      '21': { lang: 'Hindi' },
      '22': { lang: 'Thai' },
      '23': { lang: 'Korean' },
      '24': { lang: 'Lithuanian' },
      '25': { lang: 'Polish' },
      '26': { lang: 'Hungarian' },
      '27': { lang: 'Estonian' },
      '28': { lang: 'Latvian' },
      '29': { lang: 'Sami' },
      '30': { lang: 'Faroese' },
      '31': { lang: 'Farsi' },
      '32': { lang: 'Russian' },
      '33': { lang: 'Chinese (simplified)' },
      '34': { lang: 'Flemish' },
      '35': { lang: 'Irish' },
      '36': { lang: 'Albanian' },
      '37': { lang: 'Romanian' },
      '38': { lang: 'Czech' },
      '39': { lang: 'Slovak' },
      '40': { lang: 'Slovenian' },
      '41': { lang: 'Yiddish' },
      '42': { lang: 'Serbian' },
      '43': { lang: 'Macedonian' },
      '44': { lang: 'Bulgarian' },
      '45': { lang: 'Ukrainian' },
      '46': { lang: 'Byelorussian' },
      '47': { lang: 'Uzbek' },
      '48': { lang: 'Kazakh' },
      '49': { lang: 'Azerbaijani (Cyrillic script)' },
      '50': { lang: 'Azerbaijani (Arabic script)' },
      '51': { lang: 'Armenian' },
      '52': { lang: 'Georgian' },
      '53': { lang: 'Moldavian' },
      '54': { lang: 'Kirghiz' },
      '55': { lang: 'Tajiki' },
      '56': { lang: 'Turkmen' },
      '57': { lang: 'Mongolian (Mongolian script)' },
      '58': { lang: 'Mongolian (Cyrillic script)' },
      '59': { lang: 'Pashto' },
      '60': { lang: 'Kurdish' },
      '61': { lang: 'Kashmiri' },
      '62': { lang: 'Sindhi' },
      '63': { lang: 'Tibetan' },
      '64': { lang: 'Nepali' },
      '65': { lang: 'Sanskrit' },
      '66': { lang: 'Marathi' },
      '67': { lang: 'Bengali' },
      '68': { lang: 'Assamese' },
      '69': { lang: 'Gujarati' },
      '70': { lang: 'Punjabi' },
      '71': { lang: 'Oriya' },
      '72': { lang: 'Malayalam' },
      '73': { lang: 'Kannada' },
      '74': { lang: 'Tamil' },
      '75': { lang: 'Telugu' },
      '76': { lang: 'Sinhalese' },
      '77': { lang: 'Burmese' },
      '78': { lang: 'Khmer' },
      '79': { lang: 'Lao' },
      '80': { lang: 'Vietnamese' },
      '81': { lang: 'Indonesian' },
      '82': { lang: 'Tagalog' },
      '83': { lang: 'Malay (Roman script)' },
      '84': { lang: 'Malay (Arabic script)' },
      '85': { lang: 'Amharic' },
      '86': { lang: 'Tigrinya' },
      '87': { lang: 'Galla' },
      '88': { lang: 'Somali' },
      '89': { lang: 'Swahili' },
      '90': { lang: 'Kinyarwanda' },
      '91': { lang: 'Rundi' },
      '92': { lang: 'Nyanja' },
      '93': { lang: 'Malagasy' },
      '94': { lang: 'Esperanto' },
      '128': { lang: 'Welsh' },
      '129': { lang: 'Basque' },
      '130': { lang: 'Catalan' },
      '131': { lang: 'Latin' },
      '132': { lang: 'Quechua' },
      '133': { lang: 'Guarani' },
      '134': { lang: 'Aymara' },
      '135': { lang: 'Tatar' },
      '136': { lang: 'Uighur' },
      '137': { lang: 'Dzongkha' },
      '138': { lang: 'Javanese (Roman script)' },
      '139': { lang: 'Sundanese (Roman script)' },
      '140': { lang: 'Galician' },
      '141': { lang: 'Afrikaans' },
      '142': { lang: 'Breton' },
      '143': { lang: 'Inuktitut' },
      '144': { lang: 'Scottish' },
      '145': { lang: 'Manx' },
      '146': { lang: 'Irish' },
      '147': { lang: 'Tongan' },
      '148': { lang: 'Greek (polytonic)' },
      '149': { lang: 'Greenlandic' },
      '150': { lang: 'Azerbaijani (Roman script)' },
    },
    Microsoft: {
      0x436: {
        lang: 'Afrikaans',
        reg: 'South Africa',
      },
      0x41c: {
        lang: 'Albanian',
        reg: 'Albania',
      },
      0x484: {
        lang: 'Alsatian',
        reg: 'France',
      },
      0x403: {
        lang: 'Catalan',
        reg: 'Catalan',
      },
      0x804: {
        lang: 'Chinese',
        reg: 'People’s Republic of China',
      },
      0x404: {
        lang: 'Chinese',
        reg: 'Taiwan',
      },
      0x405: {
        lang: 'Czech',
        reg: 'Czech Republic',
      },
      0x406: {
        lang: 'Danish',
        reg: 'Denmark',
      },
      0x413: {
        lang: 'Dutch',
        reg: 'Netherlands',
      },
      0x409: {
        lang: 'English',
        reg: 'United States',
      },
      0x809: {
        lang: 'English',
        reg: 'United Kingdom',
      },
      0x407: {
        lang: 'German',
        reg: 'Germany',
      },
      0x408: {
        lang: 'Greek',
        reg: 'Greece',
      },
      0x410: {
        lang: 'Italian',
        reg: 'Italy',
      },
      0x411: {
        lang: 'Japanese',
        reg: 'Japan',
      },
      0x412: {
        lang: 'Korean',
        reg: 'Korea',
      },
      0x414: {
        lang: 'Norwegian',
        reg: '(Bokmal)	Norway',
      },
      0x415: {
        lang: 'Polish',
        reg: 'Poland',
      },
      0x416: {
        lang: 'Portuguese',
        reg: 'Brazil',
      },
      0x816: {
        lang: 'Portuguese',
        reg: 'Portugal',
      },
      0x418: {
        lang: 'Romanian',
        reg: 'Romania',
      },
      0x417: {
        lang: 'Romansh',
        reg: 'Switzerland',
      },
      0x419: {
        lang: 'Russian',
        reg: 'Russia',
      },
    },
  }

  const language = languages[platform][id] ?? {}

  language.id = id

  return language
}

export default mapLanguageId
